name: Node.js CI on push

on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run backend Mocha tests
        run: npm run test
        working-directory: backend
        env:
          EMAILHOST: smtp.ethereal.email
          EMAILUSER: graham.casper61@ethereal.email
          EMAILPASSWORD: ${{secrets.EMAILPASSWORD}}
          EMAILPORT: 587
          SECRET: ${{secrets.SECRET}}

  build:
    name: 'Publish to dockerhub'
    needs: [backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish production version to Dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lumawelhot/luma-varaukset:latest
          build-args: |
            PUBLIC_URL=https://luma-varaukset.cs.helsinki.fi
#      - name: Publish staging version to Dockerhub
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: lumawelhot/luma-varaukset:staging
#          build-args: |
#            PUBLIC_URL=https://ohtup-staging.cs.helsinki.fi/luma-varaukset
