name: Node.js CI on pull request

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci && cd ../backend && npm ci && cd ../frontend
      - run: npm run build --if-present
      - name: Run Jest tests
        run: npm run test -- --coverage --watchAll=false --collectCoverageFrom="src/components/**/*js"
        working-directory: frontend
      - uses: codecov/codecov-action@v1
        with:
          flags: frontend # optional
          name: codecov-umbrella # optional
      - name: Start backend for Cypress
        run: cd ../backend && nohup npm run dev &
        env:
          SECRET: ${{ secrets.SECRET }}
          PORT: 3001
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          working-directory: frontend
          wait-on: http://localhost:3000
          wait-on-timeout: 300
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_KEY}}
          #MONGODB_TEST_URI: ${{secrets.MONGODB_TEST_URI}}
          SECRET: ${{secrets.SECRET}}

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run eslint
        run: npm run lint
        working-directory: backend
      - name: Run backend Jest tests
        run: npm run test -- --coverage
        working-directory: backend
        env:
          #MONGODB_TEST_URI: ${{secrets.MONGODB_TEST_URI}}
          SECRET: ${{secrets.SECRET}}
      - uses: codecov/codecov-action@v1
        with:
          flags: backend # optional
          name: codecov-umbrella # optional
