name: Node.js CI on push

on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci && cd ../backend && npm ci && cd ../frontend
      - run: npm run build --if-present
      - name: Run Jest tests
        run: npm run test -- --watchAll=false
        working-directory: frontend
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start, npm run dev --prefix ../backend/
          working-directory: frontend
          wait-on: http://localhost:3000
          wait-on-timeout: 300
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_KEY}}
          #MONGODB_TEST_URI: ${{secrets.MONGODB_TEST_URI}}
          SECRET: ${{secrets.SECRET}}

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run backend Jest tests
        run: npm run test -- --detectOpenHandles=false
        working-directory: backend
        env:
          #MONGODB_TEST_URI: ${{secrets.MONGODB_TEST_URI}}
          EMAILHOST: smtp.ethereal.email
          EMAILUSER: clarabelle.terry@ethereal.email
          EMAILPASSWORD: ${{secrets.EMAILPASSWORD}}
          EMAILPORT: 587
          SECRET: ${{secrets.SECRET}}

  build:
    name: 'Publish to dockerhub'
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to Dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lumawelhot/luma-varaukset
          tags: latest
